
export type Language = 'en' | 'zh';

export const translations: { [key: string]: { [lang in Language]: string } } = {
  // App.tsx
  appName: { en: 'PIXEL TRAVEL MAP', zh: '像素旅行地图' },
  addMemory: { en: 'Add Memory', zh: '添加回忆' },
  hammerAddBuilding: { en: 'Add building from photo', zh: '从照片添加建筑' },
  cameraCapture: { en: 'Capture photo for building', zh: '拍摄并添加建筑' },
  reset: { en: 'Reset', zh: '重置' },
  resetMap: { en: 'Reset map', zh: '重置地图' },
  showHelp: { en: 'Show help', zh: '显示帮助' },
  toggleLanguage: { en: 'Toggle language', zh: '切换语言' },
  welcomeTitle: { en: 'ECHO MAP', zh: 'ECHO MAP' },
  welcomeSubtitle: { en: 'Upload travel photos to create a 3D map of your adventures.', zh: '上传旅行照片，创建你冒险的3D地图。' },
  welcomeInstructions: { en: 'Drag & drop, paste, or use the upload button.', zh: '拖放、粘贴或使用上传按钮。' },
  toastLocationFound: { en: 'Location found! Placing your memory in', zh: '已找到位置！正在放置您的回忆于' },
  toastNoLocationFound: { en: 'No location found. Placing memory at drop point.', zh: '未找到位置。在拖放点放置回忆。' },
  placementPrompt: { en: 'No location data found. Click anywhere on the map to place your model.', zh: '未找到位置数据。请在地图上点击任意位置以放置您的模型。' },
  placementPromptWithBuilding: {
    en: 'Could not auto-locate from "{{name}}". Click the map to place your model — AI generation still uses this building name.',
    zh: '未能根据「{{name}}」自动定位。请点击地图放置；生成 3D 建筑时仍会使用该名称。',
  },
  selectedLocation: { en: 'Selected location', zh: '选定的位置' },
  droppedLocation: { en: 'Dropped Location', zh: '拖放的位置' },
  loadingLocation: { en: 'Loading location...', zh: '加载位置中...' },
  importMap: { en: 'Import', zh: '导入' },
  exportMap: { en: 'Export', zh: '导出' },
  loadingExport: { en: 'Preparing your map...', zh: '正在准备您的地图...' },
  loadingImport: { en: 'Importing your memories...', zh: '正在导入您的回忆...' },
  errorInvalidFile: { en: 'Invalid map file. Please select a valid `.pixmap` file.', zh: '无效的地图文件。请选择一个有效的 `.pixmap` 文件。' },
  importSuccess: { en: 'Map imported successfully!', zh: '地图导入成功！' },
  
  // ImportConfirmModal.tsx
  importConfirmTitle: { en: 'Replace current map?', zh: '替换当前地图吗？' },
  importConfirmMessage: { en: 'This will replace your current map with the contents of the file. All unsaved changes will be lost.', zh: '这将用文件内容替换您当前的地图。所有未保存的更改都将丢失。' },

  // SearchControl.tsx
  searchPlaceholder: { en: 'Search location...', zh: '搜索位置...' },
  searchButton: { en: 'Search', zh: '搜索' },

  // HelpModal.tsx
  helpTitle: { en: 'Controls', zh: '操作说明' },
  helpDragMapKey: { en: 'Drag Map', zh: '拖动地图' },
  helpDragMapValue: { en: 'Pan View', zh: '平移视图' },
  helpMouseWheelKey: { en: 'Mouse Wheel', zh: '鼠标滚轮' },
  helpMouseWheelValue: { en: 'Zoom View', zh: '缩放视图' },
  helpRegenerate: { en: 'Regenerate', zh: '重新生成' },
  helpFlip: { en: 'Flip', zh: '翻转' },
  helpDuplicate: { en: 'Duplicate', zh: '复制' },
  helpShowOriginal: { en: 'Show Original', zh: '显示原图' },
  helpScale: { en: 'Scale Object', zh: '缩放对象' },
  helpDeleteKey: { en: 'Backspace', zh: '退格键' },
  helpDelete: { en: 'Delete', zh: '删除' },
  helpArrowKeysKey: { en: 'Arrow keys', zh: '方向键' },
  helpArrowKeysValue: { en: 'Move Object', zh: '移动对象' },
  helpFooter: { en: 'Image generation via Vertex AI (Gemini)', zh: '图像生成使用 Vertex AI（Gemini）' },
  helpAiTitle: { en: 'AI-generated buildings', zh: 'AI 生成建筑图' },
  helpAiBody: {
    en: 'Building images are generated by AI (Google Vertex / Gemini) from your photos. Outputs may be imperfect; you are responsible for how you use them in public. Do not upload others’ photos without permission.',
    zh: '建筑图由 AI（Google Vertex / Gemini）根据你的照片生成，可能存在偏差；公开使用内容由你自行负责。请勿上传未获授权他人影像。',
  },
  addBuildingAiNote: {
    en: 'By uploading, you confirm you have rights to the image and accept AI processing under our terms.',
    zh: '上传即表示你确认拥有图片使用权并同意按说明进行 AI 处理。',
  },
  buildingStyleLabel: { en: 'Building style', zh: '建筑风格' },
  buildingStyle_flat: { en: 'Flat illustration art', zh: '扁平插画风' },
  buildingStyle_pixel: { en: 'Pixel art', zh: '像素风' },
  buildingStyle_ink: { en: 'Ink painting art', zh: '水墨风' },
  buildingStyle_healing: { en: 'Healing illustration art', zh: '治愈绘本风' },
  toastFileTooLarge: {
    en: 'File too large (max 10MB).',
    zh: '文件过大（最大 10MB）。',
  },
  toastMapNotReady: {
    en: 'Map is still loading. Please try again in a moment.',
    zh: '地图仍在加载，请稍后再试。',
  },
  toastPlacementNoGeoHint: {
    en: 'No place name detected in the title. Click the map to place your building.',
    zh: '标题中未识别到地名，请点击地图放置建筑。',
  },
  toastGeocodeFailedManual: {
    en: 'Could not find that place on the map. Click anywhere to finish placing.',
    zh: '无法在地图上找到该地点，请点击地图任意位置完成放置。',
  },
  toastGenerationFailed: {
    en: 'Image generation failed. Showing your original photo.',
    zh: '生成失败，已显示原始照片。',
  },

  // ResetConfirmModal.tsx
  resetConfirmTitle: { en: 'Reset map?', zh: '重置地图？' },
  confirm: { en: 'Confirm', zh: '确认' },
  cancel: { en: 'Cancel', zh: '取消' },

  // Toolbar.tsx
  toolbarRotate: { en: 'Rotate / Regenerate', zh: '旋转 / 重新生成' },
  toolbarMirror: { en: 'Mirror', zh: '镜像' },
  toolbarRegenerate: { en: 'Regenerate', zh: '重新生成' },
  toolbarFlip: { en: 'Flip', zh: '翻转' },
  toolbarDuplicate: { en: 'Duplicate', zh: '复制' },
  toolbarScaleUp: { en: 'Scale Up', zh: '放大' },
  toolbarScaleDown: { en: 'Scale Down', zh: '缩小' },
  toolbarDelete: { en: 'Delete', zh: '删除' },
  toolbarLock: { en: 'Lock Memory', zh: '锁定回忆' },
  toolbarEditPlaceholder: { en: 'Remix this...', zh: 'Remix this...' },
  toolbarApplyEdit: { en: 'Apply edit', zh: '应用编辑' },

  // MemoryCards.tsx
  cardsEditLog: { en: 'Edit Travel Log', zh: '编辑旅行日志' },
  cardsViewPhoto: { en: 'View photo', zh: '查看照片' },
  cardsPhotoThumbnailAlt: { en: 'Memory thumbnail', zh: '回忆缩略图' },
  cardsDeletePhoto: { en: 'Delete photo', zh: '删除照片' },
  cardsAddPhoto: { en: 'Add Photo', zh: '添加照片' },
  cardsUnlock: { en: 'Unlock to Edit', zh: '解锁以编辑' },

  // PhotoPreviewModal.tsx
  previewAltText: { en: 'Memory preview {{current}} of {{total}}', zh: '回忆预览 {{current}} / {{total}}' },
  previewClose: { en: 'Close photo preview', zh: '关闭照片预览' },
  previewPrevious: { en: 'Previous photo', zh: '上一张照片' },
  previewNext: { en: 'Next photo', zh: '下一张照片' },

  // TravelLogModal.tsx
  logTitle: { en: 'Travel Log', zh: '旅行日志' },
  logLocation: { en: 'Location', zh: '位置' },
  logDate: { en: 'Date', zh: '日期' },
  logMusings: { en: 'Mood', zh: '心情 / 随笔' },
  logPartner: { en: 'Partner', zh: '同行伙伴' },
  logMusingsPlaceholder: { en: 'Your story...', zh: '你的故事...' },
  save: { en: 'Save', zh: '保存' },

  // AuthPanel + cloud (Supabase)
  authDisabledHint: {
    en: 'Cloud save: add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env (see .env.example). Local map still works.',
    zh: '云端登录：在 .env 中配置 VITE_SUPABASE_URL 与 VITE_SUPABASE_ANON_KEY（见 .env.example）。不配也可本地使用地图。',
  },
  authLoading: { en: 'Checking session…', zh: '正在检查登录状态…' },
  authSignedInAs: { en: 'Signed in', zh: '已登录' },
  authSignOut: { en: 'Sign out', zh: '退出登录' },
  authSignIn: { en: 'Sign in', zh: '登录' },
  authSignUp: { en: 'Register', zh: '注册' },
  authEmailPlaceholder: { en: 'Email', zh: '邮箱' },
  authPasswordPlaceholder: { en: 'Password', zh: '密码' },
  authSubmitSignIn: { en: 'Sign in', zh: '登录' },
  authSubmitSignUp: { en: 'Create account', zh: '创建账号' },
  authCheckEmail: {
    en: 'Check your email to confirm (if required by your Supabase project).',
    zh: '若项目开启了邮箱确认，请查收邮件完成验证后再登录。',
  },
  cloudPull: { en: 'Load map from cloud', zh: '从云端加载地图' },
  cloudPushAll: { en: 'Save all to cloud', zh: '全部保存到云端' },
  cloudPullConfirm: {
    en: 'Replace the current map with your cloud data? Unsaved local changes on this device will be lost.',
    zh: '用云端数据替换当前地图？本机未上传的修改将丢失。',
  },
  cloudPullOk: { en: 'Loaded from cloud.', zh: '已从云端加载。' },
  cloudPullFailed: { en: 'Could not load from cloud.', zh: '从云端加载失败。' },
  cloudPushOk: { en: 'Saved {{count}} building(s) to cloud.', zh: '已上传 {{count}} 个建筑到云端。' },
  cloudPushFailed: { en: 'Cloud save failed.', zh: '上传到云端失败。' },
  cloudSaveFailed: { en: 'Could not auto-save to cloud.', zh: '自动保存到云端失败。' },
};
